#!/bin/bash

jot()(

	# Cd to jot dir, pull any changes and potentially create a new md file.
	set -e
	cd $JOTS_DIR
	POSITIONAL=()

	# Parse arguments.
	while [[ "$#" -gt 0 ]]; do
		case $1 in
			#-l|--list) list="$2"; shift ;;
			-l|--list)
				echo "List jots from oldest modified to newest"
				echo "----------------------------------------\n"
				ls -tr *.md | grep -v README ;
				exit 0;;
			-h|--help)
				echo "Jots\n"
				echo 'Use like "jot notes"'
				echo ""
				echo "Additional commands supported are:"
				echo "-l|--list) List jots"
				echo "-h|--help) View help"
				exit 0;;
			*)
				POSITIONAL+=("$1")
				shift
				;;
		esac
	done

	set -- "${POSITIONAL[@]}" # restore positional parameters


	FNAME=$1.md
	touch $FNAME
	git pull -q

	# Open editor while checking if contents changed.
	TEXT_COPY=$(cat $FNAME)
	$JOT_EDITOR $FNAME
	TEXT_COPY_AFTER=$(cat $FNAME)

	# Push any changes.
	if [ "$TEXT_COPY" != "$TEXT_COPY_AFTER" ]; then
		git add $FNAME
		git commit -m "updated $FNAME" -q
		git push origin master -q
	fi
)
